### ISSUE TITLE
e621 Mod Settings

### ISSUE THREAD

**Issue by TaserTheFox** [Emik03/loselose#5]
So either I'm somehow building it wrong, or,
The mod settings folder doesn't seem to get created, if it is, them I cant find the mod settings almost anywhere, and the ones I found, doesn't seem to do anything.

Possibly related, https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=7e19728fc4477624213855457581f81bde3f2bc1;bomb=EB0IF6
the module fails to read the JSON file, and throws an error, using default values instead.

> JSON reading failed with error After parsing a value an unexpected character was encountered: ". Path 'allowExplicit', line 3, position 2., extracting default values.

This was with a fresh download from this repo, followed by building it without any changes.

**Comment by Emik03** [comment]
The `modSettings.json` folder needs to be in the root of `Assets/`, which I have done in the commit 14b8ca9. Try rebuilding again, and the file should bundle in the root of `build/`.

**Comment by TaserTheFox** [comment]
https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=ce55725320976c3697d875a7a35e3ea9935d2d04;bomb=N40IA7
still causing a parse issue, 
also its building directly to my mods folder.

**Comment by Emik03** [comment]
According to [Qkrisi's documentation](https://github.com/Qkrisi/ktanemodkit/wiki/KMModSettings#kmmodsettings), it reads from the mod directory root. Do you have a `modSettings.json` located in your root, and have you modified it based on the settings you want?

**Comment by TaserTheFox** [comment]
well its still failing to parse the file anyway. also what do you mean root mods folder? the "Cursed modules" folder in the ktane commons folder?

**Comment by Emik03** [comment]
"cursedModules" folder, yeah. I don't get how it fails to parse the JSON file when it just flat out is a valid one.

**Comment by TaserTheFox** [comment]
I just changed the default to what I want, but that isn't a viable solution long term... whatever that means... considering what the module contains.

**Comment by Emik03** [comment]
You could hack together a solution like the default being something you have control over during runtime, such as the existence of a file, or even an environment variable, as awful of a solution as that is.

**Comment by TaserTheFox** [comment]
im not that good with C# lmao, I can change a few things here and there, and thats about it

**Comment by Emik03** [comment]
Compile with [this scuffed branch](https://github.com/Emik03/loselose/tree/allowExplicit-bodge), a new file should appear called `e621` in `%userprofile%\AppData\LocalLow\Steel Crate Games\Keep Talking and Nobody Explodes\`. Will consider this resolved, since I do not maintain these modules anymore, I won't bother fixing bugs related to them.
